apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "daily-api.fullname" . }}-tweet
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "0 6,13,18 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
{{- include "daily-api.checksum" . | indent 12 }}
        spec:
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["node", "bin/tweet-trending.js"]
              env:
{{ include "daily-api.config" . | indent 10 }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "daily-api.fullname" . }}-views
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
{{- include "daily-api.checksum" . | indent 12 }}
        spec:
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["node", "bin/update-views.js"]
              env:
{{ include "daily-api.config" . | indent 10 }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "daily-api.fullname" . }}-tags
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "7 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
{{- include "daily-api.checksum" . | indent 12 }}
        spec:
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["node", "bin/update-tags.js"]
              env:
{{ include "daily-api.config" . | indent 10 }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "daily-api.fullname" . }}-webflow
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "3 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
{{- include "daily-api.checksum" . | indent 12 }}
        spec:
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["node", "bin/update-webflow.js"]
              env:
{{ include "daily-api.config" . | indent 10 }}
          restartPolicy: OnFailure
