apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "daily-api.fullname" . }}
  labels:
    app: {{ template "daily-api.name" . }}
    chart: {{ template "daily-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "daily-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
{{- include "daily-api.checksum" . | indent 8 }}
      labels:
        app: {{ template "daily-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
          - name: PORT
            value: "3000"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/etc/config/serviceAccount.json"
{{ include "daily-api.config" . | indent 10 }}
          volumeMounts:
          - name: config
            mountPath: "/etc/config"
            readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: config
        secret:
          secretName: {{ template "daily-api.fullname" . }}-files
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ template "daily-api.name" . }}
                  - key: release
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
