apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "daily-api.fullname" . }}-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ template "daily-api.name" . }}
      release: {{ .Release.Name }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "daily-api.fullname" . }}-bg-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: {{ template "daily-api.name" . }}-bg
      release: {{ .Release.Name }}